//GET SEARCH STOCKS
export const GET_STOCKS = "GET_STOCKS";
export const GET_STOCKS_SUCCESS = "GET_STOCKS_SUCCESS";
export const GET_STOCKS_ERROR = "GET_STOCKS_ERROR";

// GET STOCK BY SYMBOL
export const GET_STOCK_BY_SYMBOL = "GET_STOCK_BY_SYMBOL";
export const GET_STOCK_BY_SYMBOL_SUCCESS = "GET_STOCK_BY_SYMBOL_SUCCESS";
export const GET_STOCK_BY_SYMBOL_ERROR = "GET_STOCK_BY_SYMBOL_ERROR";
