export const SEARCH_STOCKS_BY_SYMBOL = "SEARCH_STOCKS_BY_SYMBOL";
export const SEARCH_STOCKS_BY_SYMBOL_SUCCESS =
  "SEARCH_STOCKS_BY_SYMBOL_SUCCESS";
export const SEARCH_STOCKS_BY_SYMBOL_ERROR = "SEARCH_STOCKS_BY_SYMBOL_SUCCESS";
